---
dockerhub_login_enabled: false
dockerhub_username: iliyasone
dockerhub_registry_url: "https://index.docker.io/v1/"

app_name: devops-python-info-service
docker_image_name: "{{ dockerhub_username }}/{{ app_name }}"
docker_image_tag: latest
docker_image: "{{ docker_image_name }}:{{ docker_image_tag }}"

app_port: 5000
app_container_port: 5000
app_container_name: "{{ app_name }}"
app_restart_policy: unless-stopped
app_wait_timeout: 60
app_healthcheck_url: "http://127.0.0.1:{{ app_port }}/health"

app_environment:
  HOST: "0.0.0.0"
  PORT: "{{ app_container_port | string }}"
  DEBUG: "false"
