---
docker_user: ubuntu

docker_repo_uri: "https://download.docker.com/linux/ubuntu"
docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo_component: "stable"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin

# Needed if you will use Ansible's Docker modules (docker_container, etc.)
docker_python_packages:
  - python3-docker

docker_prereq_packages:
  - ca-certificates
  - curl
  # deb822_repository needs python3-debian on the managed node
  - python3-debian
