replicaCount: 3

image:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  nodePort: null

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

env:
  APP_VERSION: "2026.04-helm-prod"
  LOG_LEVEL: INFO
